# source: https://faun.pub/continuous-integration-of-java-project-with-github-actions-7a8a0e8246ef
name: CI-CD operations PUSH event MAIN branch pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  # https://github.com/mathieudutour/github-tag-action
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
    outputs:
      tag_name: ${{ steps.tag_version.outputs.new_tag }}

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [ 'AgentProductService', 'AgentReportService','AgentShopService' ] }
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish artifact on GitHub Packages
        working-directory: ${{ matrix.dir }}
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v1
      - name: Build product service docker image
        run: bash ./publish-dockerhub.sh ${{ needs.release.outputs.tag_name }} ${{ secrets.DOCKER_USER }} ${{ secrets.DOCKER_PASS }}